version: "3"

services:
  server:
    container_name: server
    build: server/
    env_file:
      - .env
    volumes:
      - .:/server
      - /server/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - mongodb
    restart: always

  mongodb:
    container_name: mongodb
    image: mongodb:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LOG_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${LOG_DB_ROOT_PASS}
    ports:
      - ${LOG_DB_PORTS}
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    restart: always

  client:
    container_name: client
    build: client/
    env_file:
      - .env
    volumes:
      - .:/client
      - /client/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - server
    restart: always
